name: ahp_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  firebase_storage: ^13.2.0

  # Google Sign-In
  google_sign_in: ^6.2.2

  # Fonts
  google_fonts: ^8.0.2

  # Animations
  animate_do: ^4.2.0

  # Image picker (profile picture)
  image_picker: ^1.1.2

  # Permissions (camera, mic, notifications)
  permission_handler: ^11.3.1

  # URL launcher (open links from profile)
  url_launcher: ^6.2.5

  # Local storage
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true