// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:132103583216:web:c0cabea7791d2666ba1935',
    messagingSenderId: '132103583216',
    projectId: 'ahp-98b04',
    authDomain: 'ahp-98b04.firebaseapp.com',
    storageBucket: 'ahp-98b04.firebasestorage.app',
    measurementId: 'G-8NVQL83C91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:132103583216:android:718958d6c70fe089ba1935',
    messagingSenderId: '132103583216',
    projectId: 'ahp-98b04',
    storageBucket: 'ahp-98b04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLkmpC6r20J6U3jZb49PRmtUvuaGRb36Q',
    appId: '1:132103583216:ios:b45fba58aff69d1aba1935',
    messagingSenderId: '132103583216',
    projectId: 'ahp-98b04',
    storageBucket: 'ahp-98b04.firebasestorage.app',
    iosBundleId: 'com.example.ahpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLkmpC6r20J6U3jZb49PRmtUvuaGRb36Q',
    appId: '1:132103583216:ios:b45fba58aff69d1aba1935',
    messagingSenderId: '132103583216',
    projectId: 'ahp-98b04',
    storageBucket: 'ahp-98b04.firebasestorage.app',
    iosBundleId: 'com.example.ahpApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi-BZpK17uKagwT7CUbMYj0su8y39A_PQ',
    appId: '1:132103583216:web:a1fe79f804c03087ba1935',
    messagingSenderId: '132103583216',
    projectId: 'ahp-98b04',
    authDomain: 'ahp-98b04.firebaseapp.com',
    storageBucket: 'ahp-98b04.firebasestorage.app',
    measurementId: 'G-VNXS49B3EP',
  );
}